### ISSUE TITLE
The installer does not seem to work

### ISSUE THREAD

**Issue by aukuste** [leycec/kiseki-linux#3]
Hi,

I tried using this installer today, but I could not get it to work, no matter what I did. After selecting all of the required files in the installer window and clicking the Continue button, the input fields for the GOG .bin file and the ZIP file for the japanese dialogue disappeared, whilst the input fields for the .dat and .dir file remained.

I could not get past the screen where you select the required files no matter what changes I tried making to the installer file.

I'm using Lutris 0.5.8.3 on Fedora 33.

Any help with this would be greatly appreciated.

If you need me to provide more information or doing testing then I'd be happy to provide both.

**Comment by leycec** [comment]
**Yikes!** This is tragic news, because I'm on the cusp of leaping from Dragon Quest XI S back into the Trails franchise. How could you do this to me at such a delicate time, Lutris?

Seriously, it sounds like Lutris 0.5.8.3 broke everything – which would be saddening, maddening, and completely unsurprising. Lutris 0.5.8.0 broke everything, too.

That said... *maybe this is us.* It's probably not. It's probably them. But even if it is them, perhaps there's some way we can hack around their breakage on our end. Lutris scripts aren't configurable at all, though. We may be Shitballs Outta Luck (SOL) on this one.

Let's spin this up and see what I see. Thanks for the detailed heads up, @aukuste! Also, welcome to GitHub. We hope you enjoy your stay. :cat2:

**Comment by leycec** [comment]
**Bwaha!** I can replicate your exact issue. As everybody and their mangy cat suspected, Lutris 0.5.8.3 (or some other recent stable release in the 0.5.x cycle) did indeed break everything. I am Jack's utter lack of astonishment.

I'll try playing with this as well on my end. My suspicion is that Lutris specifically broke caching *yet again.* If true, then unchecking all of the "Cache file for future installations" check boxes will make worky. Of course, that probably won't help. As a last-ditch heroic effort to salvage this, I'll then try reordering all of the assets in the YAML file. <sup>*...this is so dumb.*</sup>

Oh, Lutris. You were once so stable and usable.

**Comment by leycec** [comment]
*Hmm...* Reordering assets improves matters. Specifically, reordering the downloads *before* the manually selected files has forced Lutris to at least download those downloads, which is a distinct improvement over doing absolutely nothing.

I also dramatically reduced the length of the human-readable labels for the manually selected files. One and/or two of these two things has helped, because TitS <sup>*love that acronym*</sup> is now installing as expected.

Oh, Lutris. You were once so gallant and heroic.

**Comment by leycec** [comment]
**Ah-ha!** That was it. Lutris now appears to require that automated downloads be listed *before* manually selected files. This is so excruciatingly dumb, but we don't make the rules. We only enforce them. I'll push out a commit in a minute or so resolving this on our end.

**Comment by leycec** [comment]
If you wouldn't mind, please download the new `lutris/2004-sora_no_kiseki_fc/sora-no-kiseki-fc-gog-voiced.yml` file hosted at this repository and try to install TitS Sky FC once more from the command line with:

```
$ lutris -i sora-no-kiseki-fc-gog-voiced.yml
```

Any joy? If so, we'll close this and [edit the official Lutris script](https://lutris.net/games/the-legend-of-heroes-trails-in-the-sky).

**Comment by aukuste** [comment]
It works wonderfully now. Thank you very much for fixing the installer.

> Hmm... Reordering assets improves matters. Specifically, reordering the downloads before the manually selected files has forced Lutris to at least download those downloads, which is a distinct improvement over doing absolutely nothing.

What a bizarre bug that is.

This installer was much better than the other GOG installer that is available on the Lutris website (couldn't get Japanese voices to work for some reason after installing TitS Sky FC using the other installer. Japanese voices worked fine on Windows somehow, can't say why though). Everything, including the Japanese voices, just works.

The effort that you've put into this is much appreciated :)

**Comment by leycec** [comment]
Oh, you're so welcome. Thanks muchly for the kind words! This is me prostrating myself in appreciation. :bowing_man: 

The TitS series deserves all our love. It is the solemn duty of weeb volunteers everywhere to preserve this unheralded masterpiece for future generations. The children of tomorrow will thank us.

Let me know if you hit any additional issues. I hope to get a similar TitS SC (Second Chapter) installer up and running soon, so maybe we'll see you there. :wink:
