### ISSUE TITLE
[Steam] Trails in the Sky FC Steam Installer Megathread

### ISSUE THREAD

**Issue by leycec** [leycec/kiseki-linux#8]
@agh1467: We summon thee! Your steaming brilliance is humbly requested.

There are three additional things (*in no particular order*) we should do to fully support the phenomenal new Steam installer for Sky FC submitted by @agh1467 at PR #7:

1. **[Publish an official Lutris-hosted Steam installer.](https://lutris.net/games/the-legend-of-heroes-trails-in-the-sky)** Based on past experience, I should *probably* be the one to do this. Lutris moderators have a tendency to ignore or delete submissions submitted by anyone else. It is what it is. That said... I should *probably* only do this after you've finalized any prospective changes to the Steam installer, @agh1467. A `zenity`-based dialog instructing the user on what to do, possibly?
2. ~~**Document Steam support in our `README.rst` documentation.** Anyone can do this! *Annnnnnnyone.*~~ :wink: 
3. ~~**Document Steam Deck support in our `README.rst` documentation.** I assume Steam Deck just kinda works, but... I've assumed many things in my life. Now I live in a cabin in the Canadian wilderness. Kids, this is where assumptions get you.~~

Thanks so much for all the hard work, @agh1467. You amaze and you stun me! :open_mouth:

**Comment by agh1467** [comment]
I'll look into these. The dialog is an interesting idea, instead of launching Config.exe as the final step since the user could still select Start Game from the launcher and the game wouldn't work (the video issue I had mentioned). Being more explicit about expectations here might be better for user experience. Lutris seems to have some built-in dialog functionality which might work for that purpose, though my experience so far with Lutris YAML manipulation does not bode well for it.

I'll look into the documentation as well. I should mostly be able to lift what I wrote in the script comments anyway.

I can also test on the Steam Deck. I wonder if there will be any re-mapping necessary, as well, I doubt that instructions about Dual Shock (the use of AntiMicroX) will be necessary while playing it through Steam as it has Steam Input, and things can be mapped in whatever way the player wants, and it _should_ detect a Dual Shock PS4 controller automatically.

**Comment by leycec** [comment]
> Lutris seems to have some built-in dialog functionality which might work for that purpose...

Yeah. I wondered about that, too. Then I remembered this is Lutris, where usually nothing works as expected or advertised. (I sigh mournfully.)

> ...my experience so far with Lutris YAML manipulation does not bode well for it.

It bodes. It bodes so much. Foreboding builds as I type this.

> I should mostly be able to lift what I wrote in the script comments anyway.

Yes! Yes! So much yes! I forgot to thank you for your extensive internal commentary, so allow me to do so now. *Thank you for your extensive internal commentary.*

> I doubt that instructions about Dual Shock (the use of AntiMicroX) will be necessary while playing it through Steam as it has Steam Input...

**Fantastic if true.** So that I can sleep tonight, I choose to believe these sweet words of joy and good comfort that you are speaking.

**Comment by leycec** [comment]
`<ping>`

**Happy 2023!** Unsurprisingly, time has passed. Surprisingly, @leycec did something. I've added extensive Steam instructions to our `README.rst` file  (derived from your internal commentary in the *amazing* Steam script you wrote). All that's left is for me to actually upload that script to the Lutris page for TitS:FC. We're almost there. The hype train is now boarding.

Thanks again for all your wonderful help. Oh – and our [**TitS:SC GOG script**](https://github.com/leycec/kiseki-linux/blob/main/lutris/2006-sora_no_kiseki_sc/sora-no-kiseki-sc-gog-voiced.yml) has also been finished... *finally.* If you'd like to make a similar Steam script at some point, that would be super swell. Until then, have a great 2023 and may the fearsome power of Estelle Bright be with you always. :muscle:

**Comment by leycec** [comment]
**Resolved.** I've now also submitted your *wondrous* Steam installer to Lutris moderation. Optimistically speaking, doing so fully resolves this long-standing issue. :smile: 

Thanks yet again for all the tremendous volunteerism. So much JRPG love!
